name: Bump Version

permissions:
  contents: write
  pull-requests: write

# Only works right now through manual requests
on:
  workflow_dispatch:
    branches: 
      - 'master'
    inputs:
      version:
        description: 'Semver type of new version (major / minor / patch)'
        required: false
        type: choice
        default: patch
        options: 
        - patch
        - minor
        - major
      workspace:
        description: 'Workspace to publish e.g. core, plugin-idfa'
        required: false
        type: string
        default: 'core'

jobs:
  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest

    steps:
    - name: Check out source
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Set Working Directory
      env: 
        IS_PLUGIN: ${{ startsWith(github.event.inputs.workspace, 'plugin-') }}
      run: |
        if ${IS_PLUGIN}; then
          echo "DIR=packages/plugins/${{github.event.inputs.workspace}}" >> $GITHUB_ENV
        else
          echo "DIR=packages/${{github.event.inputs.workspace}}" >> $GITHUB_ENV
        fi
        echo "Setting working directory to: WORKSPACE=$DIR"

    - name: Bump Version
      working-directory: ${{env.DIR}}
      run: yarn version --${{ github.event.inputs.version }} --no-git-tag-version
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: 'chore: release ${{env.DIR}} ${{github.event.inputs.version}}'
        title: 'chore: release ${{env.DIR}} ${{github.event.inputs.version}}'
        delete-branch: true
