name: CD

permissions:
  contents: write

# Only works right now through manual requests
on:
  push:
    branches:
      - 'cdActions'
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver type of new version (major / minor / patch)'
        required: false
        type: choice
        default: patch
        options: 
        - patch
        - minor
        - major
      workspace:
        description: 'Workspace to release'
        required: false
        type: string
        default: '@segment/analytics-react-native'

jobs:
  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest

    steps:
    - name: Check out source
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: Set Environment Variables
      env: 
        IS_PUSH: ${{ github.event_name  == 'push' }}
      run: |
        if ${IS_PUSH}; then
          echo "VERSION=patch" >> $GITHUB_ENV
          echo "WORKSPACE='@segment/analytics-react-native'" >> $GITHUB_ENV
          echo "Set the default input params: VERSION=patch, WORKSPACE='@segment/analytics-react-native'"
        else
          echo "VERSION=${{github.event.inputs.version}}" >> $GITHUB_ENV
          echo "WORKSPACE=${{github.event.inputs.workspace}}" >> $GITHUB_ENV
          echo "Setting user input params: VERSION=${{github.event.inputs.version}}, WORKSPACE=${{github.event.inputs.workspace}}"
        fi
    

    - name: Bump Version (no tag)
      if: github.event.inputs.workspace != 'core'
      run: yarn workspace ${{ env.WORKSPACE }} version --${{ env.VERSION }} --no-git-tag-version

    - name: Bump Version (tag)
      if: github.event.inputs.workspace == 'core'
      run: yarn workspace ${{ env.WORKSPACE }} version --${{ env.VERSION }}

    - name: Push latest version
      run: echo 'git push origin master --follow-tags'
  
  # publish:
  #   name: Publish to NPM
  #   needs: bump-version
  #   uses: ./.github/workflows/publish.yml
  #   with:
  #     workspace: ${{ env.WORKSPACE }}
  #   secrets:
  #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
