on: 
  issues:
    types:
      - opened

jobs:
  create_jira:
    runs-on: ubuntu-latest
    environment: IssueTracker
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}

    - name: Create
      id: create
      uses: ./
      with:
        project: Libraries - Mobile
        issuetype: Bug
        summary: |
          [${{ github.event.repository.name }}] (${{ github.event.issue.number }}): ${{ github.event.issue.title }}
        description: |
          Github Link: ${{ github.event.issue.html_url }}
          ${{ github.event.issue.body }}
        fields: '{"component": "analytics-react-native"}'

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"