name: Publish

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
    paths:
    # Only supporting core for now
      - 'packages/core/**'
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Workspace to publish e.g. core, plugin-idfa'
        required: false
        type: string
        default: 'core'
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Config and Build
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          yarn install --frozen-lockfile
          yarn build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set Working Directory
        env: 
          IS_PLUGIN: ${{ startsWith(github.event.inputs.workspace, 'plugin-') }}
        run: |
          if ${IS_PLUGIN}; then
            echo "DIR=packages/plugins/${{github.event.inputs.workspace}}" >> $GITHUB_ENV
          else
            echo "DIR=packages/${{github.event.inputs.workspace}}" >> $GITHUB_ENV
          fi
          echo "Setting working directory to: WORKSPACE=$DIR"

      - name: Publish
        working-directory: ${{env.DIR}}
        run: npm publish --tag beta --dry-run
        
  create-github-release:
    if: github.event.inputs.workspace == '' || github.event.inputs.workspace == 'core'
    name: Create GitHub Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: publish
    steps:        
      - name: Create Release Notes
        uses: actions/github-script@v4.0.2

        with:
          script: |
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              tag_name: "${{ github.ref }}",
              generate_release_notes: true,
              draft: true
            });