name: Publish

on:
  push:
    tags:
      - 'v*'
    paths:
      - 'packages/core/**'
  # workflow_dispatch:
  #   inputs:
  #     workspace:
  #       description: 'Workspace to publish e.g. @segment/analytics-react-native'
  #       required: false
  #       type: string
  #       default: '@segment/analytics-react-native'
  #   secrets:
  #     NPM_TOKEN:
  #       required: true

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Config and Build
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          yarn install --frozen-lockfile
          yarn build --frozen-lockfile
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: npm publish --tag beta --dry-run
        
  create-github-release:
    if: github.event.inputs.workspace == '@segment/analytics-react-native'
    name: Create GitHub Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: publish
    steps:        
      - name: Create Release Notes
        uses: actions/github-script@v4.0.2

        with:
          script: |
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              tag_name: "${{ github.ref }}",
              generate_release_notes: true,
              draft: true
            });